version: '3.8'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "source ./secrets.sh && rm -f tmp/pids/server.pid && bin/rails db:migrate && bundle exec rails assets:precompile && bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
      IPINFO_API_TOKEN: ${IPINFO_API_TOKEN}